version: "3"

services:
  postgres:
    container_name: postgres_pr
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    # таблицы и их содержимое
    - ./db_data/testing/postgres/:/var/lib/postgresql/data
    - ./db_data/testing/run/postgres.sock:/var/run/postgres/postgres.sock
    env_file:
    - docker.db.testing.env